name: CI Tests

on: [push, pull_request]

jobs:
  typescript-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Run tests
        env:
          BITCOIN_RPC_URL: ${{ secrets.BITCOIN_RPC_URL }}
          BITCOIN_RPC_USERNAME: ${{ secrets.BITCOIN_RPC_USERNAME }}
          BITCOIN_RPC_PASSWORD: ${{ secrets.BITCOIN_RPC_PASSWORD }}
        run: bun run test
